### ISSUE TITLE
Can I use your application for testing?

### ISSUE THREAD

**Issue by miguelitolaparra** [laurensk/JetDriver-App#2]
Hello.
Congratulations for your work, I like it a lot to continue learning, I am a React Native Rookie

Please excuse me for disturbing you and taking up some of his time.
I only want to ask you a few questions that you will answer if you wish.
1 - Can I use your application for testing?

2 - If I can use your application, what files does the registry system have to be able to use it completely?

Thanks again, I apologize for disturbing you.
a cordial greeting
Michael Thick

**Comment by laurensk** [comment]
Hey @miguelitolaparra, of course, can you use this project for testing purposes. It would be best to set up your own instance of the backend service so you don't mess with the prod database and service. Take a look at this repository: https://github.com/laurensk/jetdriver-api

I hope I could help!
Laurens
